/*
MetaFab API

Complete MetaFab API references and guides can be found at: https://trymetafab.com

API version: 1.5.1
Contact: metafabproject@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metafab

import (
	"encoding/json"
)

// CreateEcosystemRequest struct for CreateEcosystemRequest
type CreateEcosystemRequest struct {
	// The name of the ecosystem you're creating.
	Name string `json:"name"`
	// The email address associated with this ecosystem and used to login/authenticate as the ecosystem.
	Email string `json:"email"`
	// The password to authenticate as the ecosystem.
	Password string `json:"password"`
}

// NewCreateEcosystemRequest instantiates a new CreateEcosystemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEcosystemRequest(name string, email string, password string) *CreateEcosystemRequest {
	this := CreateEcosystemRequest{}
	this.Name = name
	this.Email = email
	this.Password = password
	return &this
}

// NewCreateEcosystemRequestWithDefaults instantiates a new CreateEcosystemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEcosystemRequestWithDefaults() *CreateEcosystemRequest {
	this := CreateEcosystemRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateEcosystemRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateEcosystemRequest) GetNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateEcosystemRequest) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CreateEcosystemRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateEcosystemRequest) GetEmailOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateEcosystemRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *CreateEcosystemRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CreateEcosystemRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CreateEcosystemRequest) SetPassword(v string) {
	o.Password = v
}

func (o CreateEcosystemRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if true {
		toSerialize["password"] = o.Password
	}
	return json.Marshal(toSerialize)
}

type NullableCreateEcosystemRequest struct {
	value *CreateEcosystemRequest
	isSet bool
}

func (v NullableCreateEcosystemRequest) Get() *CreateEcosystemRequest {
	return v.value
}

func (v *NullableCreateEcosystemRequest) Set(val *CreateEcosystemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEcosystemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEcosystemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEcosystemRequest(val *CreateEcosystemRequest) *NullableCreateEcosystemRequest {
	return &NullableCreateEcosystemRequest{value: val, isSet: true}
}

func (v NullableCreateEcosystemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEcosystemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


