/*
MetaFab API

Complete MetaFab API references and guides can be found at: https://trymetafab.com

API version: 1.5.1
Contact: metafabproject@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metafab

import (
	"encoding/json"
)

// CreateWalletSignatureRequest struct for CreateWalletSignatureRequest
type CreateWalletSignatureRequest struct {
	// The plaintext message to sign.
	Message string `json:"message"`
}

// NewCreateWalletSignatureRequest instantiates a new CreateWalletSignatureRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWalletSignatureRequest(message string) *CreateWalletSignatureRequest {
	this := CreateWalletSignatureRequest{}
	this.Message = message
	return &this
}

// NewCreateWalletSignatureRequestWithDefaults instantiates a new CreateWalletSignatureRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWalletSignatureRequestWithDefaults() *CreateWalletSignatureRequest {
	this := CreateWalletSignatureRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *CreateWalletSignatureRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CreateWalletSignatureRequest) GetMessageOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CreateWalletSignatureRequest) SetMessage(v string) {
	o.Message = v
}

func (o CreateWalletSignatureRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableCreateWalletSignatureRequest struct {
	value *CreateWalletSignatureRequest
	isSet bool
}

func (v NullableCreateWalletSignatureRequest) Get() *CreateWalletSignatureRequest {
	return v.value
}

func (v *NullableCreateWalletSignatureRequest) Set(val *CreateWalletSignatureRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWalletSignatureRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWalletSignatureRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWalletSignatureRequest(val *CreateWalletSignatureRequest) *NullableCreateWalletSignatureRequest {
	return &NullableCreateWalletSignatureRequest{value: val, isSet: true}
}

func (v NullableCreateWalletSignatureRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWalletSignatureRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


