/*
MetaFab API

 Complete MetaFab API references and guides can be found at: https://trymetafab.com

API version: 1.4.1
Contact: metafabproject@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metafab

import (
	"encoding/json"
)

// CreateCollectionItemRequestAttributesInner struct for CreateCollectionItemRequestAttributesInner
type CreateCollectionItemRequestAttributesInner struct {
	TraitType string `json:"trait_type"`
	Value interface{} `json:"value"`
}

// NewCreateCollectionItemRequestAttributesInner instantiates a new CreateCollectionItemRequestAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCollectionItemRequestAttributesInner(traitType string, value interface{}) *CreateCollectionItemRequestAttributesInner {
	this := CreateCollectionItemRequestAttributesInner{}
	this.TraitType = traitType
	this.Value = value
	return &this
}

// NewCreateCollectionItemRequestAttributesInnerWithDefaults instantiates a new CreateCollectionItemRequestAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCollectionItemRequestAttributesInnerWithDefaults() *CreateCollectionItemRequestAttributesInner {
	this := CreateCollectionItemRequestAttributesInner{}
	return &this
}

// GetTraitType returns the TraitType field value
func (o *CreateCollectionItemRequestAttributesInner) GetTraitType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TraitType
}

// GetTraitTypeOk returns a tuple with the TraitType field value
// and a boolean to check if the value has been set.
func (o *CreateCollectionItemRequestAttributesInner) GetTraitTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TraitType, true
}

// SetTraitType sets field value
func (o *CreateCollectionItemRequestAttributesInner) SetTraitType(v string) {
	o.TraitType = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CreateCollectionItemRequestAttributesInner) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCollectionItemRequestAttributesInner) GetValueOk() (*interface{}, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CreateCollectionItemRequestAttributesInner) SetValue(v interface{}) {
	o.Value = v
}

func (o CreateCollectionItemRequestAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["trait_type"] = o.TraitType
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCollectionItemRequestAttributesInner struct {
	value *CreateCollectionItemRequestAttributesInner
	isSet bool
}

func (v NullableCreateCollectionItemRequestAttributesInner) Get() *CreateCollectionItemRequestAttributesInner {
	return v.value
}

func (v *NullableCreateCollectionItemRequestAttributesInner) Set(val *CreateCollectionItemRequestAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCollectionItemRequestAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCollectionItemRequestAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCollectionItemRequestAttributesInner(val *CreateCollectionItemRequestAttributesInner) *NullableCreateCollectionItemRequestAttributesInner {
	return &NullableCreateCollectionItemRequestAttributesInner{value: val, isSet: true}
}

func (v NullableCreateCollectionItemRequestAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCollectionItemRequestAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


