/*
MetaFab API

Complete MetaFab API references and guides can be found at: https://trymetafab.com

API version: 1.5.1
Contact: metafabproject@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metafab

import (
	"encoding/json"
)

// EcosystemGameModel struct for EcosystemGameModel
type EcosystemGameModel struct {
	// This field has not had a description added.
	Id *string `json:"id,omitempty"`
	// This field has not had a description added.
	EcosystemId *string `json:"ecosystemId,omitempty"`
	// This field has not had a description added.
	GameId *string `json:"gameId,omitempty"`
	// This field has not had a description added.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// This field has not had a description added.
	CreatedAt *string `json:"createdAt,omitempty"`
}

// NewEcosystemGameModel instantiates a new EcosystemGameModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEcosystemGameModel() *EcosystemGameModel {
	this := EcosystemGameModel{}
	return &this
}

// NewEcosystemGameModelWithDefaults instantiates a new EcosystemGameModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEcosystemGameModelWithDefaults() *EcosystemGameModel {
	this := EcosystemGameModel{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EcosystemGameModel) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcosystemGameModel) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EcosystemGameModel) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EcosystemGameModel) SetId(v string) {
	o.Id = &v
}

// GetEcosystemId returns the EcosystemId field value if set, zero value otherwise.
func (o *EcosystemGameModel) GetEcosystemId() string {
	if o == nil || isNil(o.EcosystemId) {
		var ret string
		return ret
	}
	return *o.EcosystemId
}

// GetEcosystemIdOk returns a tuple with the EcosystemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcosystemGameModel) GetEcosystemIdOk() (*string, bool) {
	if o == nil || isNil(o.EcosystemId) {
    return nil, false
	}
	return o.EcosystemId, true
}

// HasEcosystemId returns a boolean if a field has been set.
func (o *EcosystemGameModel) HasEcosystemId() bool {
	if o != nil && !isNil(o.EcosystemId) {
		return true
	}

	return false
}

// SetEcosystemId gets a reference to the given string and assigns it to the EcosystemId field.
func (o *EcosystemGameModel) SetEcosystemId(v string) {
	o.EcosystemId = &v
}

// GetGameId returns the GameId field value if set, zero value otherwise.
func (o *EcosystemGameModel) GetGameId() string {
	if o == nil || isNil(o.GameId) {
		var ret string
		return ret
	}
	return *o.GameId
}

// GetGameIdOk returns a tuple with the GameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcosystemGameModel) GetGameIdOk() (*string, bool) {
	if o == nil || isNil(o.GameId) {
    return nil, false
	}
	return o.GameId, true
}

// HasGameId returns a boolean if a field has been set.
func (o *EcosystemGameModel) HasGameId() bool {
	if o != nil && !isNil(o.GameId) {
		return true
	}

	return false
}

// SetGameId gets a reference to the given string and assigns it to the GameId field.
func (o *EcosystemGameModel) SetGameId(v string) {
	o.GameId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *EcosystemGameModel) GetUpdatedAt() string {
	if o == nil || isNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcosystemGameModel) GetUpdatedAtOk() (*string, bool) {
	if o == nil || isNil(o.UpdatedAt) {
    return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *EcosystemGameModel) HasUpdatedAt() bool {
	if o != nil && !isNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *EcosystemGameModel) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *EcosystemGameModel) GetCreatedAt() string {
	if o == nil || isNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EcosystemGameModel) GetCreatedAtOk() (*string, bool) {
	if o == nil || isNil(o.CreatedAt) {
    return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *EcosystemGameModel) HasCreatedAt() bool {
	if o != nil && !isNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *EcosystemGameModel) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o EcosystemGameModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.EcosystemId) {
		toSerialize["ecosystemId"] = o.EcosystemId
	}
	if !isNil(o.GameId) {
		toSerialize["gameId"] = o.GameId
	}
	if !isNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !isNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableEcosystemGameModel struct {
	value *EcosystemGameModel
	isSet bool
}

func (v NullableEcosystemGameModel) Get() *EcosystemGameModel {
	return v.value
}

func (v *NullableEcosystemGameModel) Set(val *EcosystemGameModel) {
	v.value = val
	v.isSet = true
}

func (v NullableEcosystemGameModel) IsSet() bool {
	return v.isSet
}

func (v *NullableEcosystemGameModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEcosystemGameModel(val *EcosystemGameModel) *NullableEcosystemGameModel {
	return &NullableEcosystemGameModel{value: val, isSet: true}
}

func (v NullableEcosystemGameModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEcosystemGameModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


