/*
MetaFab API

Complete MetaFab API references and guides can be found at: https://trymetafab.com

API version: 1.5.1
Contact: metafabproject@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metafab

import (
	"encoding/json"
)

// UpdateProfileRequest struct for UpdateProfileRequest
type UpdateProfileRequest struct {
	// The profile's current password. Must be provided if setting `newPassword`.
	CurrentPassword *string `json:"currentPassword,omitempty"`
	// A new password. The profile's old password will no longer be valid.
	NewPassword *string `json:"newPassword,omitempty"`
	// Revokes the profile's previous access token and returns a new one if true.
	ResetAccessToken *bool `json:"resetAccessToken,omitempty"`
}

// NewUpdateProfileRequest instantiates a new UpdateProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileRequest() *UpdateProfileRequest {
	this := UpdateProfileRequest{}
	return &this
}

// NewUpdateProfileRequestWithDefaults instantiates a new UpdateProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileRequestWithDefaults() *UpdateProfileRequest {
	this := UpdateProfileRequest{}
	return &this
}

// GetCurrentPassword returns the CurrentPassword field value if set, zero value otherwise.
func (o *UpdateProfileRequest) GetCurrentPassword() string {
	if o == nil || isNil(o.CurrentPassword) {
		var ret string
		return ret
	}
	return *o.CurrentPassword
}

// GetCurrentPasswordOk returns a tuple with the CurrentPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileRequest) GetCurrentPasswordOk() (*string, bool) {
	if o == nil || isNil(o.CurrentPassword) {
    return nil, false
	}
	return o.CurrentPassword, true
}

// HasCurrentPassword returns a boolean if a field has been set.
func (o *UpdateProfileRequest) HasCurrentPassword() bool {
	if o != nil && !isNil(o.CurrentPassword) {
		return true
	}

	return false
}

// SetCurrentPassword gets a reference to the given string and assigns it to the CurrentPassword field.
func (o *UpdateProfileRequest) SetCurrentPassword(v string) {
	o.CurrentPassword = &v
}

// GetNewPassword returns the NewPassword field value if set, zero value otherwise.
func (o *UpdateProfileRequest) GetNewPassword() string {
	if o == nil || isNil(o.NewPassword) {
		var ret string
		return ret
	}
	return *o.NewPassword
}

// GetNewPasswordOk returns a tuple with the NewPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileRequest) GetNewPasswordOk() (*string, bool) {
	if o == nil || isNil(o.NewPassword) {
    return nil, false
	}
	return o.NewPassword, true
}

// HasNewPassword returns a boolean if a field has been set.
func (o *UpdateProfileRequest) HasNewPassword() bool {
	if o != nil && !isNil(o.NewPassword) {
		return true
	}

	return false
}

// SetNewPassword gets a reference to the given string and assigns it to the NewPassword field.
func (o *UpdateProfileRequest) SetNewPassword(v string) {
	o.NewPassword = &v
}

// GetResetAccessToken returns the ResetAccessToken field value if set, zero value otherwise.
func (o *UpdateProfileRequest) GetResetAccessToken() bool {
	if o == nil || isNil(o.ResetAccessToken) {
		var ret bool
		return ret
	}
	return *o.ResetAccessToken
}

// GetResetAccessTokenOk returns a tuple with the ResetAccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileRequest) GetResetAccessTokenOk() (*bool, bool) {
	if o == nil || isNil(o.ResetAccessToken) {
    return nil, false
	}
	return o.ResetAccessToken, true
}

// HasResetAccessToken returns a boolean if a field has been set.
func (o *UpdateProfileRequest) HasResetAccessToken() bool {
	if o != nil && !isNil(o.ResetAccessToken) {
		return true
	}

	return false
}

// SetResetAccessToken gets a reference to the given bool and assigns it to the ResetAccessToken field.
func (o *UpdateProfileRequest) SetResetAccessToken(v bool) {
	o.ResetAccessToken = &v
}

func (o UpdateProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CurrentPassword) {
		toSerialize["currentPassword"] = o.CurrentPassword
	}
	if !isNil(o.NewPassword) {
		toSerialize["newPassword"] = o.NewPassword
	}
	if !isNil(o.ResetAccessToken) {
		toSerialize["resetAccessToken"] = o.ResetAccessToken
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateProfileRequest struct {
	value *UpdateProfileRequest
	isSet bool
}

func (v NullableUpdateProfileRequest) Get() *UpdateProfileRequest {
	return v.value
}

func (v *NullableUpdateProfileRequest) Set(val *UpdateProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileRequest(val *UpdateProfileRequest) *NullableUpdateProfileRequest {
	return &NullableUpdateProfileRequest{value: val, isSet: true}
}

func (v NullableUpdateProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


